name: Test Manual Only

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "This should only run manually with input: ${{ github.event.inputs.test_input }}"